development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: avnerner
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: avnerner
  password: 
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: avnerner
  password: 
  host: localhost